### ISSUE TITLE
AsyncWorldEdit issue with certain worldedit commands.

### ISSUE THREAD

**Issue by minecraftian4304** [SBPrime/AsyncWorldEdit#270] opened 2019-11-15 05:05 UTC
I am experiencing an issue with AsyncWorldEdit where certain worldedit commands return a java.util.ConcurrentModificationExeption: null

This error appears when doing basic commands like //set <blockname>
Any advice on how to fix this?

**Comment by SBPrime** [comment] 2019-11-15 05:48
You need to provide:
1. Spigot username
2. Full server startup log,
3. Log for the operation that fails with log level set to debug

**Comment by minecraftian4304** [comment] 2019-11-15 14:45
spigot username: mhall119
current server logs: https://hasteb.in/uxuvocuk.md I am not sure how to get the debug logs.

**Comment by minecraftian4304** [comment] 2019-11-16 18:07
If it helps, I am noticing that it only happens in certain worlds, like the spawn world, but other worlds, like the minigames world, im not getting that issue, every thing works perfectly.

**Comment by SBPrime** [comment] 2019-11-17 21:14
Without the debug log I won't be able to help. I'm 99% sure that you get the error because you are using CoreProtect without BlocksHub.

To enable debug mode in the config search for LogLevel and set it to DEBUG.
To run AWE with CoreProtect you need to install BlocksHub, disable WE integration in CP and enable BlocksHib integration in AWE.

**Comment by minecraftian4304** [comment] 2019-11-17 22:07
ok thanks! I will try that fix and try to get the debug logs when I get the
time.

**Comment by trickman325** [comment] 2019-11-25 11:07
i have the same issue, this is my console after i try to perform the //set command.
https://pastebin.com/GeK0cgJi
i have never had the issue before until i installed the latest update. was working perfectly with core protect WITHOUT having blockshub.

**Comment by SBPrime** [comment] 2019-11-26 05:51
@trickman325 This problem is not related to CP. Its related to com.vexsoftware.votifier, please send log for the set operation with log level set to debug and spigot user name.

**Comment by trickman325** [comment] 2019-11-26 10:55
@SBPrime how do i set log level to debug? ive done a /debug is that it?
https://pastebin.com/YrnY69dC
that is the /debug run with the //set command in the spawn world (where it works) and then once again in the survival world (where i get the error)

**Comment by SBPrime** [comment] 2019-11-26 12:58
As I said this problem is most likely caused by votifier. Do enable debug mode in AWE go to config and change the log level to DEBUG.

**Comment by trickman325** [comment] 2019-11-28 00:06
that is my level set to debug after runnning the //set stone command
https://pastebin.com/yzu6B6zi
My username is Arcticmankey

**Comment by SBPrime** [comment] 2019-11-28 06:04
I need the full log with debug enabled, especially the part when you enter the command, with is not available in the log that you provided.

**Comment by trickman325** [comment] 2019-11-29 01:52
[2019-11-29-3.log.gz](https://github.com/SBPrime/AsyncWorldEdit/files/3903400/2019-11-29-3.log.gz)
that file is thw whole log from restart, doing the command, then another restart.
all commands work fine in our other worlds. it is only failing when using the //set and trying to use the brush in survival world.

**Comment by SBPrime** [comment] 2019-11-29 05:56
@trickman325 The problem is caused by lack of compatibility for AWE in lands. Unfortunately since its a premium plugin it won't be fixed on my end. The fix needs to be introduced by the lands author. The only thing that you can do is look for lands in the class scanner results and add it to the blacklist in AWE config.
As a final note please remember that full support on how to setup and configure the plugin is available for premium users.

**Comment by SBPrime** [comment] 2019-11-29 05:57
@minecraftian4304 Any update?

**Comment by SBPrime** [comment] 2019-12-16 21:18
No update closing.

**Closed by SBPrime** 2019-12-16 21:18 UTC
