### ISSUE TITLE
Brushes aren't working

### ISSUE THREAD

**Issue by metalshark** [SBPrime/AsyncWorldEdit#292] opened 2020-02-16 13:33 UTC
Any attempt to use a brush does not work and results in errors to the console:
https://paste.gg/p/metalshark/7697d129fdc44732855b0b9c79239253

Am on the latest version 7.1.0 of WorldEdit and 3.6.18 of AsyncWorldEdit Premium.

**Comment by therealatsuga** [comment] 2020-02-29 11:57
Same....  can confirm. 

https://codeshare.io/5X1loz

**Comment by SBPrime** [comment] 2020-03-14 21:00
Duplicate of #296 please comment there.

**Closed by SBPrime** 2020-03-14 21:00 UTC
