### ISSUE TITLE
Class scanner encountered an error while scanning class

### ISSUE THREAD

**Issue by MrSpock78** [SBPrime/AsyncWorldEdit#195] opened 2018-12-13 14:06 UTC
AWE 3.6.0-rc-02
WE 7.0.0-SNAPSHOT;3963-700e41b
WG 7.0.0-SNAPSHOT;1763-80aec37
Paper 1.13.2-480

AWE: https://hastebin.com/waladodoto.sql
WE: https://hastebin.com/yazutihazi.bash

**Comment by MrSpock78** [comment] 2018-12-15 12:32
Sorry debug on is killing my server with massive outputs in logs. It creates about 200MB(!!!) log until the server crashes.
The normal log without debug:
https://pastebin.com/4QTLwtsG

Warning on enabling AWE:
[13:20:35] [Server thread/INFO]: [AsyncWorldEdit] Warning: Unable to get class com.sk89q.worldedit.extent.reorder.MultiStageReorder$Stage3Committer

**Comment by SBPrime** [comment] 2018-12-15 15:05
Ok but can you reproduce it?

Did you try bete 03 from here: https://dev.bukkit.org/projects/worldedit/files

The debug can be enabled for single operation then disabled. You can do it by starting the plugin in normal mode, then (before executing the command) go to awe config enable debug and do awe reload all, do the command and then disable debug and do awe reload all.

**Comment by SBPrime** [comment] 2018-12-15 17:34
Ok, so WE beta 3 works how about beta 4? I targeted beta 3 in the last release. If it works then I would say its because changes in WE.

**Comment by MrSpock78** [comment] 2018-12-15 17:41
WE beta04 causes the same errors with WG-Extra Flags enabled. 
Without WG-Extra Flags everything is fine on beta04.

**Comment by SBPrime** [comment] 2018-12-15 17:44
As far as I know WG-Extra Flags is not compatible with AWE, what version are you using (can I have a link)?. If you could provide the log when WG flags are enabled I can make sure that this is the same one that I know of.

**Comment by MrSpock78** [comment] 2018-12-15 17:47
I tried both versions of WG-Extra Flags:
https://www.spigotmc.org/resources/worldguard-extra-flags.4823/
and latest Dev-Version
https://jenkins.isokissa3.fi/job/WorldGuardExtraFlags/

**Comment by SBPrime** [comment] 2018-12-15 18:57
The error was from class scanner or a different error?

**Comment by MrSpock78** [comment] 2018-12-15 19:06
Yes always the same error: https://pastebin.com/4QTLwtsG
First AWE error followed by WE error a few seconds later.
Takes a few seconds, nothing is build with "//set ...".

**Comment by SBPrime** [comment] 2018-12-16 09:37
Fixed in rc-03

**Closed by SBPrime** 2018-12-16 09:37 UTC
