### ISSUE TITLE
IllegalStateException on regen

### ISSUE THREAD

**Issue by EvilOlaf** [SBPrime/AsyncWorldEdit#90] opened 2015-03-21 13:16 UTC
```
 [AsyncWorldEdit] Error performing safe operation for Survival cx:233 cy:22 Loaded: false, inUse: true. Error: java.lang.IllegalStateException: Asynchronous chunk load!
``` 

This happened at the execution of a //regen command which worked as expected. Just curious  about this error message. Also was not reproducible.

Spigot 1.8 (not 1.8.3) with AWE 2.1.5 and WE 6.0.2-SNAPSHOT;3347-fe6717a0

**Comment by SBPrime** [comment] 2015-04-02 17:44
Duplicate of #89

**Closed by SBPrime** 2015-04-02 17:44 UTC
